# Generated by Django 3.1.7 on 2021-04-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_auto_20210415_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[('1', 'Высокий'), ('2', 'Средний'), ('3', 'Низкий')], default=0, null=True),
        ),
    ]
