# Generated by Django 3.1.7 on 2021-04-16 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0008_auto_20210415_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('1', 'Высокий'), ('2', 'Средний'), ('3', 'Низкий')], max_length=10, null=True),
        ),
    ]
